### PR TITLE
[WIP] 2.12 support, MonadErrorTests broken

### PR DESCRIPTION
**Pull request by Krever**
Hi,

I tried to add support for Scala 2.12 but it was harder that I thought. Following errors came up:
1. MonadErrorTests has broken, running it effects in "Maximum call stack size exceeded"
2. My implementation of scalacheck Cogen may be wrong, I have very little experience with it and I just followed method signatures

I don't have enough knowledge to pursuit  it further but maybe someone would like to take it from here.

### CODE REVIEW

**Comment by julienrf** [comment]
Super nice!
I tried to add 2.12 support too, a few weeks ago, but it implies to upgrade cats and maintaining the tests that check the laws is not super easy…
I will have a look this week-end.

**Comment by julienrf** [comment]
> MonadErrorTests has broken, running it effects in "Maximum call stack size exceeded"

That’s because our implementation of `tailRecM` is not stack-safe and cats now includes a test that checks stack-safety. I’m currently looking for a solution.

> My implementation of scalacheck Cogen may be wrong, I have very little experience with it and I just followed method signatures

Anyway, implementing `CoFlatMap` makes no sense… I will just remove that.

**Comment by julienrf** [comment]
I pushed my work in progress here but some tests still fail: https://github.com/Krever/faithful/compare/2.12_support...julienrf:krever-2.12-support

**Comment by julienrf** [comment]
For information, Scala.js 0.6.15 contains a fix that makes it possible to run the tests now :)

**Comment by julienrf** [comment]
Hey, everything is fine now, I merged your PR, thanks!

**Comment by Krever** [comment]
Great news, thanks :)

**Pull request merged**
